### ISSUE TITLE
ＢＧＭの実装を

### ISSUE THREAD

**Issue by 165b012** [tanakaedu/yoketoru-unity-2016#19]
タイトルから（ゲームオーバー/クリア）まで

**Comment by 165b012** [comment]
- [ ] BGMにする曲選び。
- [ ] BGMがなるようにする。
- [ ] タイトル、ゲーム画面、クリア/ゲームオーバーに切り替えてもBGMが途切れないように鳴らし続ける。

**Comment by tanakaedu** [comment]
- 296add8 で実装完了
- BGM
  - Zero Gravity
  - Jon Hillman Media, LLC
  - http://u3d.as/4h3
